import type { Metadata } from 'next';
import './globals.css';
import NextAuthSessionProvider from './NextAuthSessionProvider';
import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
  title: {
    default: 'demo',
    template: '%s | demo',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
